version: '3'

services:
  mysql:
    image: mysql
    container_name: spring-car-rental-db
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_password}"
      MYSQL_DATABASE: car_rental
    ports:
      - "${db_port}:3306"
    networks:
      - network-spring-car-rental

  beadando:
    image: spokieh/car-rental-java
    container_name: spring-car-rental
    environment:
      MYSQL_HOST: spring-car-rental-db
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: car_rental
      MYSQL_USER: "${mysql_user}"
      MYSQL_PASSWORD: "${mysql_password}"
    ports:
      - "${service_port}:8080"
    networks:
      - network-spring-car-rental

networks:
  network-spring-car-rental:
    driver: bridge
